name: Java CI with JDK 21 on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Windows runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 21 (Windows)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          architecture: x64  # Optional, but good for specifying the architecture

      # Compile Java code (without Maven)
      - name: Compile Java code
        run: |
          javac Calculator.java CalculatorTest.java

      # Run tests
      - name: Run tests
        run: |
          java CalculatorTest
