name: Java CI with JDK 21 on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use the Windows runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 21 (Windows)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'  # Specify the distribution
          architecture: x64

      # Compile Java code (without Maven)
      - name: Compile Java code
        run: |
          javac Calculator.java CalculatorTest.java

      # Run tests
      - name: Run JUnit tests
        run: |
          java -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore CalculatorTest
