name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Build the project (without Maven)
      - name: Compile Java code
        run: |
          javac Calculator.java CalculatorTest.java

      # Run tests
      - name: Run tests
        run: |
          java CalculatorTest
