name: Java CI with JDK 21 on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Change from ubuntu-latest to windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 21 (Windows)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      # Compile Java code (without Maven)
      - name: Compile Java code
        run: |
          javac Calculator.java CalculatorTest.java

      # Run tests
      - name: Run JUnit tests
        run: |
          java -cp CalculatorTest
